In [ ]:
import torch
import numpy as np

In [ ]:
data = [[2,3],[4,5]]

In [ ]:
x_data = torch.tensor(data)
x_data

tensor([[2, 3],
        [4, 5]])

In [ ]:
np_arr = np.array(data)
np_arr

array([[2, 3],
       [4, 5]])

In [ ]:
x_from_np = torch.from_numpy(np_arr)
x_from_np

tensor([[2, 3],
        [4, 5]])

In [ ]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_zeros = torch.zeros_like(x_data)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [ ]:
x_rand = torch.rand_like(x_data)
x_rand

RuntimeError: ignored

In [ ]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.2592, 0.5363],
        [0.7514, 0.2371]], dtype=torch.float64)

In [ ]:
shape = (2,3)
x_ones_from_shape = torch.ones(shape)
x_ones_from_shape

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
shape = (2,3,)
x_ones_from_shp = torch.ones(shape)
x_ones_from_shp

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x_rand_from_shp = torch.randint(shape)
x_rand_from_shp

TypeError: ignored

In [ ]:
x_rand_from_shp = torch.randint(10, shape)
x_rand_from_shp

In [ ]:
print(f'shape: {x_data.shape}')
print(f'data type: {x_data.dtype}')
print(f'device: {x_data.device}')

shape: torch.Size([2, 2])
data type: torch.int64
device: cpu


In [ ]:
if torch.cuda.is_available():
    x_data = x_data.to('cuda')
    print('moved to cuda')

moved to cuda


In [ ]:
x_data = torch.rand((2,3))

In [22]:
x_datas = torch.cat([x_data, x_data])
x_datas

tensor([[0.2015, 0.6875, 0.9077],
        [0.1885, 0.3110, 0.3168],
        [0.2015, 0.6875, 0.9077],
        [0.1885, 0.3110, 0.3168]], device='cuda:0')

In [23]:
y_datas = torch.cat([x_data, x_data], dim = 1)
y_datas

tensor([[0.2015, 0.6875, 0.9077, 0.2015, 0.6875, 0.9077],
        [0.1885, 0.3110, 0.3168, 0.1885, 0.3110, 0.3168]], device='cuda:0')

In [25]:
print(f'transpose: {x_datas.T}')

transpose: tensor([[0.2015, 0.1885, 0.2015, 0.1885],
        [0.6875, 0.3110, 0.6875, 0.3110],
        [0.9077, 0.3168, 0.9077, 0.3168]], device='cuda:0')


In [26]:
print(x_datas.shape, y_datas.shape)

torch.Size([4, 3]) torch.Size([2, 6])


In [28]:
x_datas = x_datas.reshape((2,6))
x_datas.shape

torch.Size([2, 6])

In [30]:
print(f'matrix maltiplicaton: {x_datas.matmul(y_datas.T)}')
print(f'matrix maltiplicaton alt syntax: {x_datas @ y_datas.T}')

matrix maltiplicaton: tensor([[1.8764, 0.7720],
        [1.8764, 0.7720]], device='cuda:0')
matrix maltiplicaton alt syntax: tensor([[1.8764, 0.7720],
        [1.8764, 0.7720]], device='cuda:0')


In [31]:
x_datas

tensor([[0.2015, 0.6875, 0.9077, 0.1885, 0.3110, 0.3168],
        [0.2015, 0.6875, 0.9077, 0.1885, 0.3110, 0.3168]], device='cuda:0')

In [32]:
x_datas.matmul(y_datas.T)
x_datas

AttributeError: ignored

In [34]:
n = np.ones((2,3))
t = torch.from_numpy(n)

In [35]:
n[0,0] = 5

In [36]:
print(n)
print(t)

[[5. 1. 1.]
 [1. 1. 1.]]
tensor([[5., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
